AWSTemplateFormatVersion: "2010-09-09" 

Description: Create an S3 bucket with a name specified that is set up to host a static website. 

Resources:
  S3Bucket: 
    Type: 'AWS::S3::Bucket'
    Properties:
      OwnershipControls:
           Rules:
                - ObjectOwnership: ObjectWriter
      BucketName: CREATE A NAME FOR YOUR BUCKET HERE
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: MyPolicy
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadForGetBucketObjects
          - Effect: Allow
          - Principal: '*'
          - Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
     
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  
    